# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180613_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='arquivo',
        ),
    ]
