# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180613_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopWords', models.BooleanField(default=True)),
                ('stemming', models.BooleanField(default=True)),
                ('tokenizer', models.BooleanField(default=True)),
                ('suavizacao', models.BooleanField(default=True)),
            ],
        ),
    ]
