# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basedados',
            options={'ordering': ['slug'], 'verbose_name': 'Base', 'verbose_name_plural': 'Bases'},
        ),
        migrations.RemoveField(
            model_name='basedados',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='basedados',
            name='description',
        ),
        migrations.RemoveField(
            model_name='basedados',
            name='id',
        ),
        migrations.RemoveField(
            model_name='basedados',
            name='image',
        ),
        migrations.RemoveField(
            model_name='basedados',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='basedados',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='basedados',
            name='etiquetas_pre_processadas',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Etiquetas Pre-Processadas'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='fim',
            field=models.CharField(default=b'', max_length=10, verbose_name=b'Fim'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='inicio',
            field=models.CharField(default=b'', max_length=10, verbose_name=b'In\xc3\xadcio'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='nomes_das_etiquetas',
            field=models.CharField(default=b'', max_length=300, verbose_name=b'Etiquetas'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='pre_processada',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name=b'Pre-Processada'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='quantidade_de_instancias',
            field=models.CharField(default=b'', max_length=300, verbose_name=b'Quantidades das Inst\xc3\xa2ncias'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='quantidade_de_processos',
            field=models.IntegerField(default=0, verbose_name=b'Quantidade de processos'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='tamanho_dos_arquivos',
            field=models.CharField(default=b'', max_length=300, verbose_name=b'Tamanhos dos arquivos'),
        ),
        migrations.AddField(
            model_name='basedados',
            name='tecnicas_pre_processamento',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=b'T\xc3\xa9cnicas de pr\xc3\xa9-processamento'),
        ),
        migrations.AlterField(
            model_name='basedados',
            name='slug',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
